name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: hello
        run: | 
          echo "Hello, world!"
      - name: run python script
        run: |
          pip3 install -r requirements.txt
          python3 ci.py
      