on: push

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps: 
    - run: | # For illustration purposes, placing the py code in a .py file is better
        import os
        print(len(os.getenv('MY_VAR')))
      shell: python
      env:
        MY_VAR: ${{ secrets.MY_SECRET }}
