name: "Unit Test"
on:
  push:
    paths:
      - test-example/**
  pull_request:
    paths:
      - test-example/**
      
  workflow_dispatch:

defaults:
  run:
    shell: bash -el {0}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v4
   
      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest test-example/ --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: junit/test-results.xml